# Generated by Django 5.0.2 on 2024-03-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('car', 'รถยนต์'), ('motorcycle', 'มอเตอร์ไซค์')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employ',
            name='role',
            field=models.CharField(choices=[('employee', 'พนักงาน'), ('admin', 'แอดมิน')], default='', max_length=20),
        ),
    ]
