# Generated by Django 4.1.2 on 2024-03-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0002_alter_car_type_alter_employ_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
