# Generated by Django 5.0.2 on 2024-03-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0002_alter_car_type_alter_employ_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rental_rate',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='car_cc',
            field=models.CharField(choices=[('125', '125'), ('150', '150'), ('300', '300'), ('650', '650')], default='125', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('manual', 'เกียร์ธรรมดา'), ('automatic', 'เกียร์ออโต')], default='manual', max_length=20),
        ),
    ]
