# Generated by Django 5.0.2 on 2024-03-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0003_remove_car_price_remove_car_rental_rate_and_more'),
        ('AppProject', '0003_rename_name_customer_firstname_remove_customer_role_and_more'),
    ]

    operations = [
    ]
