# Generated by Django 5.0.2 on 2024-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0004_merge_20240304_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('enable', 'พร้อมให้เช่า'), ('disibled', 'ไม่พร้อมให้เช่า')], default='พร้อมให้เช่า', max_length=20),
        ),
    ]
