# Generated by Django 5.0.2 on 2024-03-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0005_car_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rental',
            new_name='RentalOrder',
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('enable', 'พร้อมให้เช่า'), ('disibled', 'ไม่พร้อมให้เช่า')], default='enable', max_length=20),
        ),
        migrations.CreateModel(
            name='RentalReture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reture_date', models.DateField(blank=True, null=True)),
                ('car_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppProject.car')),
                ('cus_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppProject.customer')),
            ],
        ),
    ]
