# Generated by Django 5.0.2 on 2024-03-05 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0006_rename_rental_rentalorder_alter_car_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalreture',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='rentalreture',
            name='cus_id',
        ),
        migrations.RemoveField(
            model_name='rentalreture',
            name='reture_date',
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='status',
            field=models.CharField(default='รอการชำระเงิน', max_length=50),
        ),
        migrations.AddField(
            model_name='rentalreture',
            name='date_reture',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rentalreture',
            name='rental_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppProject.rentalorder'),
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.CharField(default='', max_length=50)),
                ('bill', models.ImageField(default='', upload_to='static/bills/')),
                ('rental_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppProject.rentalorder')),
            ],
        ),
        migrations.CreateModel(
            name='RentalService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_servic', models.DateTimeField(default=django.utils.timezone.now)),
                ('rental_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppProject.rentalorder')),
            ],
        ),
    ]
