# Generated by Django 5.0.2 on 2024-03-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0008_remove_rentalpayment_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalservice',
            old_name='date_servic',
            new_name='date_service',
        ),
    ]
